In [1]:
# Example DOI list
dois = [
    "doi.org/10.1038/s41591-019-0726-6",
]

In [2]:
import requests
import pandas as pd
import time
from itertools import islice


# Split a list into chunks of specified size
def chunk_list(iterable, size):
    it = iter(iterable)
    while True:
        chunk = list(islice(it, size))
        if not chunk:
            break
        yield chunk


# Clean DOI strings by removing common prefixes
def clean_doi(doi):
    prefixes_to_remove = [
        "https://doi.org/",
        "http://doi.org/",
        "doi.org/",
        "DOI:",
        "doi:",
        "https://dx.doi.org/",
        "http://dx.doi.org/",
    ]

    cleaned_doi = doi.strip()
    for prefix in prefixes_to_remove:
        if cleaned_doi.startswith(prefix):
            cleaned_doi = cleaned_doi[len(prefix) :]
            break

    return cleaned_doi


# Fetch publication metadata from OpenAlex API with retry mechanism
def get_publication_data(dois, retries=3, delay=5):
    all_results = []
    cleaned_dois = [clean_doi(doi) for doi in dois]
    print(f"Cleaned DOIs: {cleaned_dois[:5]}...")

    for chunk in chunk_list(cleaned_dois, 50):
        pipe_separated_dois = "|".join(chunk)
        url = f"https://api.openalex.org/works?filter=doi:{pipe_separated_dois}&per-page=50"
        print(f"Fetching -- {url}")

        for attempt in range(retries):
            try:
                response = requests.get(url, timeout=10)
                print(f"Response: {response.status_code}")
                if response.status_code == 200:
                    results = response.json().get("results", [])
                    print(f"Found {len(results)} publications in this chunk")
                    all_results.extend(results)
                    break
                else:
                    print(
                        f"Error {response.status_code} fetching DOIs, retrying... ({attempt+1}/{retries})"
                    )
            except requests.exceptions.RequestException as e:
                print(f"Request error: {e}, retrying... ({attempt+1}/{retries})")

            time.sleep(delay)

    print(f"Total publications found: {len(all_results)}")
    return all_results


# Extract grant information from publication data safely
def extract_grants(publication):
    grants_extracted = []
    grants_data = publication.get("grants", [])

    if not isinstance(grants_data, list):
        return grants_extracted

    for grant in grants_data:
        if not isinstance(grant, dict):
            continue

        funder_info = grant.get("funder", {})
        if not isinstance(funder_info, dict):
            continue

        grants_extracted.append(
            {
                "funder": funder_info.get("display_name", None),
                "funder_id": funder_info.get("id", None),
                "award_id": grant.get("award_id", None),
            }
        )

    return grants_extracted


# Extract keywords as a list of display names
def extract_keywords(publication):
    kw_data = publication.get("keywords", [])
    if not isinstance(kw_data, list):
        return []

    keywords_list = []
    for kw in kw_data:
        if isinstance(kw, dict):
            display_name = kw.get("display_name")
            if display_name:
                keywords_list.append(display_name)

    return keywords_list


# Country code to country name mapping
COUNTRY_CODE_TO_NAME = {
    "US": "USA",
    "GB": "United Kingdom",
    "CA": "Canada",
    # ... (other mappings)
    "NP": "Nepal",
}


# Extract relevant metadata from publication list
def extract_publication_data(publication_data):
    publication_rows = []

    for publication in publication_data:
        authorships = publication.get("authorships", [])
        if not isinstance(authorships, list):
            continue

        keywords_list = extract_keywords(publication)

        all_authors = []
        all_affiliations = []
        all_countries = []

        for author in authorships:
            author_name = author.get("author", {}).get("display_name", None)
            if author_name:
                all_authors.append(author_name)

            author_affiliation = ""
            author_country = ""

            institution_info = author.get("institutions")
            if (
                institution_info
                and isinstance(institution_info, list)
                and len(institution_info) > 0
            ):
                primary_inst = institution_info[0]
                if isinstance(primary_inst, dict):
                    aff = primary_inst.get("display_name")
                    if aff:
                        author_affiliation = aff

                    ctry_code = primary_inst.get("country_code")
                    if ctry_code:
                        ctry_name = COUNTRY_CODE_TO_NAME.get(ctry_code, ctry_code)
                        author_country = ctry_name

            all_affiliations.append(author_affiliation)
            all_countries.append(author_country)

        publication_row = {
            "id": publication.get("id", None),
            "title": publication.get("title", None),
            "display_name": publication.get("display_name", None),
            "all_authors": "; ".join(all_authors) if all_authors else "",
            "all_affiliations": "; ".join(all_affiliations) if all_affiliations else "",
            "all_countries": "; ".join(all_countries) if all_countries else "",
            "doi": publication.get("doi", None),
            "publication_date": publication.get("publication_date", None),
            "publication_year": publication.get("publication_year", None),
            "type": publication.get("type", None),
            "language": publication.get("language", None),
            "open_access": publication.get("open_access", {}).get("is_oa", None),
            "open_access_status": publication.get("open_access", {}).get(
                "oa_status", None
            ),
            "open_access_url": publication.get("open_access", {}).get("oa_url", None),
            "cited_by_count": publication.get("cited_by_count", None),
            "keywords": "; ".join(keywords_list) if keywords_list else "",
            "grants": (
                "; ".join(
                    [
                        grant.get("funder", "")
                        for grant in extract_grants(publication)
                        if grant.get("funder")
                    ]
                )
                if extract_grants(publication)
                else ""
            ),
        }

        publication_rows.append(publication_row)

    return publication_rows


# Order DataFrame according to original DOI list and handle missing entries
def order_by_doi_sequence(df, original_dois):
    cleaned_original_dois = [clean_doi(doi) for doi in original_dois]

    if df.empty:
        na_rows = [
            {
                "id": "N/A",
                "title": "N/A",
                "display_name": "N/A",
                "all_authors": "N/A",
                "all_affiliations": "N/A",
                "all_countries": "N/A",
                "doi": f"https://doi.org/{doi}",
                "publication_date": "N/A",
                "publication_year": "N/A",
                "type": "N/A",
                "language": "N/A",
                "open_access": "N/A",
                "open_access_status": "N/A",
                "open_access_url": "N/A",
                "cited_by_count": "N/A",
                "keywords": "N/A",
                "grants": "N/A",
            }
            for doi in cleaned_original_dois
        ]
        return pd.DataFrame(na_rows)

    def extract_doi_from_url(doi_url):
        if pd.isna(doi_url) or not doi_url:
            return ""
        return (
            doi_url.replace("https://doi.org/", "")
            if doi_url.startswith("https://doi.org/")
            else doi_url
        )

    found_dois = set(extract_doi_from_url(doi) for doi in df["doi"])

    missing_dois = [doi for doi in cleaned_original_dois if doi not in found_dois]

    na_rows = [
        {
            "id": "N/A",
            "title": "N/A",
            "display_name": "N/A",
            "all_authors": "N/A",
            "all_affiliations": "N/A",
            "all_countries": "N/A",
            "doi": f"https://doi.org/{doi}",
            "publication_date": "N/A",
            "publication_year": "N/A",
            "type": "N/A",
            "language": "N/A",
            "open_access": "N/A",
            "open_access_status": "N/A",
            "open_access_url": "N/A",
            "cited_by_count": "N/A",
            "keywords": "N/A",
            "grants": "N/A",
        }
        for doi in missing_dois
    ]

    df_with_na = (
        pd.concat([df, pd.DataFrame(na_rows)], ignore_index=True) if na_rows else df
    )

    doi_to_order = {doi: i for i, doi in enumerate(cleaned_original_dois)}

    df_with_na["doi_order"] = df_with_na["doi"].apply(
        lambda x: doi_to_order.get(extract_doi_from_url(x), 999999)
    )

    df_ordered = (
        df_with_na.sort_values("doi_order")
        .drop(columns=["doi_order"])
        .reset_index(drop=True)
    )

    return df_ordered


# Fetch publication data
print("Starting data extraction...")
data = get_publication_data(dois)
print(f"Processing {len(data)} publications...")

if not data:
    print("No data extracted. Adding N/A rows...")
    df_final = order_by_doi_sequence(pd.DataFrame(), dois)
else:
    records = extract_publication_data(data)
    df = pd.DataFrame(records)

    seen_ids = set()
    indices_to_keep = [
        i
        for i, pub_id in enumerate(df["id"])
        if not (pub_id in seen_ids or seen_ids.add(pub_id))
    ]

    df_deduplicated = df.iloc[indices_to_keep].reset_index(drop=True)

    df_final = order_by_doi_sequence(df_deduplicated, dois)

# Save results to CSV
df_final.to_csv("publication_data_enhanced_(1).csv", index=False)
print("Data saved to publication_data_enhanced_(93-94).csv")
print(df_final[["title", "all_authors", "all_affiliations", "all_countries"]].head(3))
print(f"Final dataset: {len(df_final)} publications (including any N/A rows)")

Starting data extraction...
Cleaned DOIs: ['10.1038/s41591-019-0726-6']...
Fetching -- https://api.openalex.org/works?filter=doi:10.1038/s41591-019-0726-6&per-page=50

Response: 200
Found 2 publications in this chunk
Total publications found: 2
Processing 2 publications...
Data saved to publication_data_enhanced_(93-94).csv
                                               title  \
0  Diagnosing bias in data-driven algorithms for ...
1  Energy Fluxes Over the Eastern Tropical Pacifi...

                                         all_authors  \
0  Jenna Wiens; W. Nicholson Price; Michael W. Sj...
1                                     Ronald K. Reed

                                    all_affiliations  all_countries
0  University of Michigan; University of Michigan...  USA; USA; USA
1
Final dataset: 2 publications (including any N/A rows)

In [3]:
df = pd.DataFrame(records)

In [4]:
df.tail(10)

,id,title,display_name,all_authors,all_affiliations,all_countries,doi,publication_date,publication_year,type,language,open_access,open_access_status,open_access_url,cited_by_count,keywords,grants
0,https://openalex.org/W3000558625,Diagnosing bias in data-driven algorithms for ...,Diagnosing bias in data-driven algorithms for ...,Jenna Wiens; W. Nicholson Price; Michael W. Sj...,University of Michigan; University of Michigan...,USA; USA; USA,https://doi.org/10.1038/s41591-019-0726-6,2020-01-01,2020,article,en,False,closed,None,62,Health care; Computer science; Data science; A...,
1,https://openalex.org/W2827076454,Energy Fluxes Over the Eastern Tropical Pacifi...,Energy Fluxes Over the Eastern Tropical Pacifi...,Ronald K. Reed,,,https://doi.org/10.1038/s41591-019-0726-6,1982-01-01,1982,article,en,False,closed,None,0,Climatology; Oceanography; Environmental scien...,

In [5]:
### EXTRACT WITH ABSTRACT

In [6]:
import requests
import pandas as pd
import time
from itertools import islice


# Split a list into chunks of specified size
def chunk_list(iterable, size):
    it = iter(iterable)
    while True:
        chunk = list(islice(it, size))
        if not chunk:
            break
        yield chunk


# Clean DOI strings by removing common prefixes
def clean_doi(doi):
    prefixes_to_remove = [
        "https://doi.org/",
        "http://doi.org/",
        "doi.org/",
        "DOI:",
        "doi:",
        "https://dx.doi.org/",
        "http://dx.doi.org/",
    ]

    cleaned_doi = doi.strip()
    for prefix in prefixes_to_remove:
        if cleaned_doi.startswith(prefix):
            cleaned_doi = cleaned_doi[len(prefix) :]
            break

    return cleaned_doi


# Fetch publication metadata from OpenAlex API with retry mechanism
def get_publication_data(dois, retries=3, delay=5):
    all_results = []
    cleaned_dois = [clean_doi(doi) for doi in dois]
    print(f"Cleaned DOIs: {cleaned_dois[:5]}...")

    for chunk in chunk_list(cleaned_dois, 50):
        pipe_separated_dois = "|".join(chunk)
        url = f"https://api.openalex.org/works?filter=doi:{pipe_separated_dois}&per-page=50"
        print(f"Fetching -- {url}")

        for attempt in range(retries):
            try:
                response = requests.get(url, timeout=10)
                print(f"Response: {response.status_code}")
                if response.status_code == 200:
                    results = response.json().get("results", [])
                    print(f"Found {len(results)} publications in this chunk")
                    all_results.extend(results)
                    break
                else:
                    print(
                        f"Error {response.status_code} fetching DOIs, retrying... ({attempt+1}/{retries})"
                    )
            except requests.exceptions.RequestException as e:
                print(f"Request error: {e}, retrying... ({attempt+1}/{retries})")

            time.sleep(delay)

    print(f"Total publications found: {len(all_results)}")
    return all_results


# Extract grant information from publication data safely
def extract_grants(publication):
    grants_extracted = []
    grants_data = publication.get("grants", [])

    if not isinstance(grants_data, list):
        return grants_extracted

    for grant in grants_data:
        if not isinstance(grant, dict):
            continue

        funder_info = grant.get("funder", {})
        if not isinstance(funder_info, dict):
            continue

        grants_extracted.append(
            {
                "funder": funder_info.get("display_name", None),
                "funder_id": funder_info.get("id", None),
                "award_id": grant.get("award_id", None),
            }
        )

    return grants_extracted


# Extract keywords as a list of display names
def extract_keywords(publication):
    kw_data = publication.get("keywords", [])
    if not isinstance(kw_data, list):
        return []

    keywords_list = []
    for kw in kw_data:
        if isinstance(kw, dict):
            display_name = kw.get("display_name")
            if display_name:
                keywords_list.append(display_name)

    return keywords_list


# Extract abstract from publication data
def extract_abstract(publication):
    """Extract abstract from publication data, handling missing abstracts gracefully"""
    abstract_data = publication.get("abstract", None)

    if abstract_data is None:
        return ""

    if isinstance(abstract_data, str):
        return abstract_data.strip()

    # Sometimes abstract might be in a different format, handle accordingly
    if isinstance(abstract_data, dict):
        # Check for common abstract fields
        for field in ["text", "content", "abstract", "summary"]:
            if field in abstract_data and abstract_data[field]:
                return str(abstract_data[field]).strip()

    return ""


# Country code to country name mapping
COUNTRY_CODE_TO_NAME = {
    "US": "USA",
    "GB": "United Kingdom",
    "CA": "Canada",
    # ... (other mappings)
    "NP": "Nepal",
}


# Extract relevant metadata from publication list
def extract_publication_data(publication_data):
    publication_rows = []

    for publication in publication_data:
        authorships = publication.get("authorships", [])
        if not isinstance(authorships, list):
            continue

        keywords_list = extract_keywords(publication)
        abstract_text = extract_abstract(publication)

        all_authors = []
        all_affiliations = []
        all_countries = []

        for author in authorships:
            author_name = author.get("author", {}).get("display_name", None)
            if author_name:
                all_authors.append(author_name)

            author_affiliation = ""
            author_country = ""

            institution_info = author.get("institutions")
            if (
                institution_info
                and isinstance(institution_info, list)
                and len(institution_info) > 0
            ):
                primary_inst = institution_info[0]
                if isinstance(primary_inst, dict):
                    aff = primary_inst.get("display_name")
                    if aff:
                        author_affiliation = aff

                    ctry_code = primary_inst.get("country_code")
                    if ctry_code:
                        ctry_name = COUNTRY_CODE_TO_NAME.get(ctry_code, ctry_code)
                        author_country = ctry_name

            all_affiliations.append(author_affiliation)
            all_countries.append(author_country)

        publication_row = {
            "id": publication.get("id", None),
            "title": publication.get("title", None),
            "display_name": publication.get("display_name", None),
            "all_authors": "; ".join(all_authors) if all_authors else "",
            "all_affiliations": "; ".join(all_affiliations) if all_affiliations else "",
            "all_countries": "; ".join(all_countries) if all_countries else "",
            "doi": publication.get("doi", None),
            "publication_date": publication.get("publication_date", None),
            "publication_year": publication.get("publication_year", None),
            "type": publication.get("type", None),
            "language": publication.get("language", None),
            "open_access": publication.get("open_access", {}).get("is_oa", None),
            "open_access_status": publication.get("open_access", {}).get(
                "oa_status", None
            ),
            "open_access_url": publication.get("open_access", {}).get("oa_url", None),
            "cited_by_count": publication.get("cited_by_count", None),
            "keywords": "; ".join(keywords_list) if keywords_list else "",
            "grants": (
                "; ".join(
                    [
                        grant.get("funder", "")
                        for grant in extract_grants(publication)
                        if grant.get("funder")
                    ]
                )
                if extract_grants(publication)
                else ""
            ),
            "abstract": abstract_text,  # Added abstract column at the end
        }

        publication_rows.append(publication_row)

    return publication_rows


# Order DataFrame according to original DOI list and handle missing entries
def order_by_doi_sequence(df, original_dois):
    cleaned_original_dois = [clean_doi(doi) for doi in original_dois]

    if df.empty:
        na_rows = [
            {
                "id": "N/A",
                "title": "N/A",
                "display_name": "N/A",
                "all_authors": "N/A",
                "all_affiliations": "N/A",
                "all_countries": "N/A",
                "doi": f"https://doi.org/{doi}",
                "publication_date": "N/A",
                "publication_year": "N/A",
                "type": "N/A",
                "language": "N/A",
                "open_access": "N/A",
                "open_access_status": "N/A",
                "open_access_url": "N/A",
                "cited_by_count": "N/A",
                "keywords": "N/A",
                "grants": "N/A",
                "abstract": "N/A",  # Added abstract field to N/A rows
            }
            for doi in cleaned_original_dois
        ]
        return pd.DataFrame(na_rows)

    def extract_doi_from_url(doi_url):
        if pd.isna(doi_url) or not doi_url:
            return ""
        return (
            doi_url.replace("https://doi.org/", "")
            if doi_url.startswith("https://doi.org/")
            else doi_url
        )

    found_dois = set(extract_doi_from_url(doi) for doi in df["doi"])

    missing_dois = [doi for doi in cleaned_original_dois if doi not in found_dois]

    na_rows = [
        {
            "id": "N/A",
            "title": "N/A",
            "display_name": "N/A",
            "all_authors": "N/A",
            "all_affiliations": "N/A",
            "all_countries": "N/A",
            "doi": f"https://doi.org/{doi}",
            "publication_date": "N/A",
            "publication_year": "N/A",
            "type": "N/A",
            "language": "N/A",
            "open_access": "N/A",
            "open_access_status": "N/A",
            "open_access_url": "N/A",
            "cited_by_count": "N/A",
            "keywords": "N/A",
            "grants": "N/A",
            "abstract": "N/A",  # Added abstract field to missing DOI rows
        }
        for doi in missing_dois
    ]

    df_with_na = (
        pd.concat([df, pd.DataFrame(na_rows)], ignore_index=True) if na_rows else df
    )

    doi_to_order = {doi: i for i, doi in enumerate(cleaned_original_dois)}

    df_with_na["doi_order"] = df_with_na["doi"].apply(
        lambda x: doi_to_order.get(extract_doi_from_url(x), 999999)
    )

    df_ordered = (
        df_with_na.sort_values("doi_order")
        .drop(columns=["doi_order"])
        .reset_index(drop=True)
    )

    return df_ordered


# Example usage (you'll need to define your DOIs list):
# dois = ["10.1038/nature12373", "10.1126/science.1234567"]  # Add your DOIs here

# Fetch publication data
print("Starting data extraction...")
data = get_publication_data(dois)
print(f"Processing {len(data)} publications...")

if not data:
    print("No data extracted. Adding N/A rows...")
    df_final = order_by_doi_sequence(pd.DataFrame(), dois)
else:
    records = extract_publication_data(data)
    df = pd.DataFrame(records)

    seen_ids = set()
    indices_to_keep = [
        i
        for i, pub_id in enumerate(df["id"])
        if not (pub_id in seen_ids or seen_ids.add(pub_id))
    ]

    df_deduplicated = df.iloc[indices_to_keep].reset_index(drop=True)

    df_final = order_by_doi_sequence(df_deduplicated, dois)

# Save results to CSV
df_final.to_csv("abstract_publication_data.csv", index=False)
print("Data saved to publication_data_enhanced_(93-94).csv")
print(
    df_final[
        ["title", "all_authors", "all_affiliations", "all_countries", "abstract"]
    ].head(3)
)
print(f"Final dataset: {len(df_final)} publications (including any N/A rows)")

Starting data extraction...
Cleaned DOIs: ['10.1038/s41591-019-0726-6']...
Fetching -- https://api.openalex.org/works?filter=doi:10.1038/s41591-019-0726-6&per-page=50

Response: 200
Found 2 publications in this chunk
Total publications found: 2
Processing 2 publications...
Data saved to publication_data_enhanced_(93-94).csv
                                               title  \
0  Diagnosing bias in data-driven algorithms for ...
1  Energy Fluxes Over the Eastern Tropical Pacifi...

                                         all_authors  \
0  Jenna Wiens; W. Nicholson Price; Michael W. Sj...
1                                     Ronald K. Reed

                                    all_affiliations  all_countries abstract
0  University of Michigan; University of Michigan...  USA; USA; USA
1
Final dataset: 2 publications (including any N/A rows)

# Full corpus enrichment — 519 papers
Loads DOIs from `dashboard/public/papers.csv`, fetches OpenAlex metadata for all papers, and outputs `openalex_enriched.csv` with:
- Abstracts (reconstructed from `abstract_inverted_index`)
- Citation counts + referenced works (for citation network analysis)
- OA status / OA URL (for license check)
- Author affiliations + countries (to fill remaining gaps)

In [7]:
import requests
import pandas as pd
import time
from itertools import islice
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
PAPERS_CSV = Path("dashboard/public/papers.csv")
OUTPUT_CSV = Path("openalex_enriched.csv")
CHUNK_SIZE = 50
DELAY      = 1.0
RETRIES    = 3

# DOI corrections: corpus has wrong/truncated DOI
DOI_OVERRIDES = {
    75: "10.48550/arxiv.2308.10149",   # truncated (was arXiv.2308.1014)
}

# Force individual re-fetch after batch (overrides wrong batch matches)
FORCE_REFETCH = {
    1: "10.1038/s41591-019-0726-6",    # batch returned wrong paper
}

COUNTRY_CODE_TO_NAME = {
    "AF":"Afghanistan","AL":"Albania","DZ":"Algeria","AR":"Argentina","AM":"Armenia",
    "AU":"Australia","AT":"Austria","AZ":"Azerbaijan","BH":"Bahrain","BD":"Bangladesh",
    "BY":"Belarus","BE":"Belgium","BO":"Bolivia","BA":"Bosnia and Herzegovina",
    "BR":"Brazil","BG":"Bulgaria","KH":"Cambodia","CA":"Canada","CL":"Chile",
    "CN":"China","CO":"Colombia","HR":"Croatia","CY":"Cyprus","CZ":"Czech Republic",
    "DK":"Denmark","EG":"Egypt","EE":"Estonia","ET":"Ethiopia","FI":"Finland",
    "FR":"France","GE":"Georgia","DE":"Germany","GH":"Ghana","GR":"Greece",
    "HK":"Hong Kong","HU":"Hungary","IN":"India","ID":"Indonesia","IR":"Iran",
    "IQ":"Iraq","IE":"Ireland","IL":"Israel","IT":"Italy","JP":"Japan",
    "JO":"Jordan","KZ":"Kazakhstan","KE":"Kenya","KR":"South Korea","KW":"Kuwait",
    "LV":"Latvia","LB":"Lebanon","LT":"Lithuania","LU":"Luxembourg","MY":"Malaysia",
    "MT":"Malta","MX":"Mexico","MA":"Morocco","NL":"Netherlands","NZ":"New Zealand",
    "NG":"Nigeria","NO":"Norway","OM":"Oman","PK":"Pakistan","PE":"Peru",
    "PH":"Philippines","PL":"Poland","PT":"Portugal","QA":"Qatar","RO":"Romania",
    "RU":"Russia","SA":"Saudi Arabia","RS":"Serbia","SG":"Singapore","SK":"Slovakia",
    "SI":"Slovenia","ZA":"South Africa","ES":"Spain","LK":"Sri Lanka","SE":"Sweden",
    "CH":"Switzerland","TW":"Taiwan","TH":"Thailand","TN":"Tunisia","TR":"Turkey",
    "UA":"Ukraine","AE":"United Arab Emirates","GB":"United Kingdom","US":"USA",
    "UY":"Uruguay","UZ":"Uzbekistan","VN":"Vietnam","MO":"Macau","NP":"Nepal",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def clean_doi(doi: str) -> str:
    doi = doi.strip()
    for prefix in ["https://doi.org/","http://doi.org/","doi.org/","DOI:","doi:",
                   "https://dx.doi.org/","http://dx.doi.org/"]:
        if doi.startswith(prefix):
            return doi[len(prefix):]
    return doi

def doi_key(doi: str) -> str:
    return clean_doi(doi).lower()

def reconstruct_abstract(publication: dict) -> str:
    aii = publication.get("abstract_inverted_index")
    if not aii or not isinstance(aii, dict):
        return ""
    wp = sorted((pos, w) for w, positions in aii.items() for pos in positions)
    return " ".join(w for _, w in wp)

def chunk_list(iterable, size):
    it = iter(iterable)
    while True:
        chunk = list(islice(it, size))
        if not chunk:
            break
        yield chunk

# ── Fetch by DOI batch (lowercase to avoid arXiv case rejection) ──────────────

def fetch_openalex(dois: list) -> list:
    all_results = []
    cleaned = [clean_doi(d).lower() for d in dois]
    for i, chunk in enumerate(chunk_list(cleaned, CHUNK_SIZE)):
        pipe = "|".join(chunk)
        url = (f"https://api.openalex.org/works"
               f"?filter=doi:{pipe}"
               f"&per-page={CHUNK_SIZE}"
               f"&select=id,doi,title,publication_year,cited_by_count,"
               f"abstract_inverted_index,referenced_works,open_access,authorships,keywords")
        print(f"Chunk {i+1}: fetching {len(chunk)} DOIs...", end=" ", flush=True)
        for attempt in range(RETRIES):
            try:
                r = requests.get(url, timeout=15)
                if r.status_code == 200:
                    results = r.json().get("results", [])
                    print(f"got {len(results)}")
                    all_results.extend(results)
                    break
                else:
                    print(f"HTTP {r.status_code}, retry {attempt+1}")
            except requests.RequestException as e:
                print(f"error: {e}, retry {attempt+1}")
            time.sleep(DELAY * 2)
        time.sleep(DELAY)
    print(f"Total fetched from batch: {len(all_results)}")
    return all_results

def fetch_single_doi(doi: str) -> dict | None:
    clean = clean_doi(doi).lower()
    url = (f"https://api.openalex.org/works/https://doi.org/{clean}"
           f"?select=id,doi,title,publication_year,cited_by_count,"
           f"abstract_inverted_index,referenced_works,open_access,authorships,keywords")
    try:
        r = requests.get(url, timeout=15)
        if r.status_code == 200:
            return r.json()
    except requests.RequestException:
        pass
    return None

def fetch_by_title(title: str) -> dict | None:
    url = (f"https://api.openalex.org/works"
           f"?search={requests.utils.quote(str(title))}"
           f"&per-page=1"
           f"&select=id,doi,title,publication_year,cited_by_count,"
           f"abstract_inverted_index,referenced_works,open_access,authorships,keywords")
    try:
        r = requests.get(url, timeout=15)
        if r.status_code == 200:
            results = r.json().get("results", [])
            if results:
                return results[0]
    except requests.RequestException:
        pass
    return None

# ── Parse ─────────────────────────────────────────────────────────────────────

def parse_work(pub: dict) -> dict:
    authorships = pub.get("authorships", []) or []
    authors, affiliations, countries = [], [], []
    for a in authorships:
        name = (a.get("author") or {}).get("display_name") or ""
        authors.append(name)
        insts = a.get("institutions") or []
        aff = insts[0].get("display_name", "") if insts else ""
        cc  = insts[0].get("country_code", "") if insts else ""
        affiliations.append(aff or "")
        countries.append(COUNTRY_CODE_TO_NAME.get(cc, cc) if cc else "")
    kws = [k["display_name"] for k in (pub.get("keywords") or [])
           if isinstance(k, dict) and k.get("display_name")]
    oa  = pub.get("open_access") or {}
    refs = [r for r in (pub.get("referenced_works") or []) if r]
    return {
        "openalex_id":           pub.get("id", ""),
        "doi":                   pub.get("doi", ""),
        "title":                 pub.get("title", ""),
        "year":                  pub.get("publication_year", ""),
        "cited_by_count":        pub.get("cited_by_count", 0),
        "abstract":              reconstruct_abstract(pub),
        "referenced_works":      "; ".join(refs),
        "is_oa":                 oa.get("is_oa", False),
        "oa_status":             oa.get("oa_status", ""),
        "oa_url":                oa.get("oa_url", ""),
        "openalex_authors":      "; ".join(authors),
        "openalex_affiliations": "; ".join(affiliations),
        "openalex_countries":    "; ".join(countries),
        "keywords":              "; ".join(kws),
    }

EMPTY_ROW = {
    "openalex_id":"", "doi":"", "title":"", "year":"", "cited_by_count":0,
    "abstract":"", "referenced_works":"", "is_oa":"", "oa_status":"", "oa_url":"",
    "openalex_authors":"", "openalex_affiliations":"", "openalex_countries":"", "keywords":""
}

# ── Main ──────────────────────────────────────────────────────────────────────

print("Loading corpus...")
corpus = pd.read_csv(PAPERS_CSV)
print(f"  {len(corpus)} papers loaded")

for sn, corrected_doi in DOI_OVERRIDES.items():
    corpus.loc[corpus["SN"] == sn, "DOI"] = corrected_doi
    print(f"  DOI override: SN {sn} -> {corrected_doi}")

dois_raw = corpus["DOI"].dropna().tolist()
print(f"  {len(dois_raw)} DOIs to fetch\n")

raw_results = fetch_openalex(dois_raw)

lookup: dict = {}
for pub in raw_results:
    key = doi_key(pub.get("doi", "") or "")
    if key:
        lookup[key] = parse_work(pub)
print(f"\nLookup table: {len(lookup)} entries")

# Build rows
rows = []
for _, row in corpus.iterrows():
    sn      = row["SN"]
    doi_raw = row["DOI"] if pd.notna(row["DOI"]) else ""
    key     = doi_key(doi_raw) if doi_raw else ""
    if key and key in lookup:
        rows.append({"SN": sn, "corpus_doi": doi_raw, **lookup[key]})
    else:
        rows.append({"SN": sn, "corpus_doi": doi_raw, **EMPTY_ROW})

sn_to_idx = {r["SN"]: i for i, r in enumerate(rows)}

# Force re-fetch for known wrong-match SNs
print("\nForce re-fetching known wrong matches...")
for sn, doi in FORCE_REFETCH.items():
    print(f"  SN {sn}...", end=" ")
    pub = fetch_single_doi(doi)
    if pub and pub.get("id"):
        rows[sn_to_idx[sn]].update(parse_work(pub))
        print(f"✓ {rows[sn_to_idx[sn]]['title'][:60]}")
    else:
        print("✗ failed")
    time.sleep(0.3)

# Individual DOI fallback for still-unmatched papers with a DOI
print("\nIndividual fallback for unmatched DOI papers...")
for i, r in enumerate(rows):
    if r["openalex_id"] == "" and r["corpus_doi"]:
        sn = r["SN"]
        print(f"  SN {sn} ({doi_key(r['corpus_doi'])[:50]})...", end=" ")
        pub = fetch_single_doi(r["corpus_doi"])
        if pub and pub.get("id"):
            rows[i].update(parse_work(pub))
            print(f"✓ {rows[i]['title'][:50]}")
        else:
            print("✗ not found via DOI, trying title...")
            title = corpus.loc[corpus["SN"] == sn, "Paper Title"].values
            if len(title):
                pub2 = fetch_by_title(title[0])
                if pub2:
                    rows[i].update(parse_work(pub2))
                    print(f"    ✓ title match: {rows[i]['title'][:50]}")
                else:
                    print(f"    ✗ not found")
        time.sleep(0.3)

# Title-search fallback for no-DOI papers
no_doi = [(r["SN"], r["corpus_doi"]) for r in rows if r["openalex_id"] == "" and not r["corpus_doi"]]
if no_doi:
    print(f"\nTitle-search for {len(no_doi)} no-DOI papers...")
    for sn, _ in no_doi:
        title = corpus.loc[corpus["SN"] == sn, "Paper Title"].values
        if not len(title):
            continue
        print(f"  SN {sn}: {str(title[0])[:60]}...", end=" ")
        pub = fetch_by_title(title[0])
        if pub:
            rows[sn_to_idx[sn]].update(parse_work(pub))
            print(f"✓ {rows[sn_to_idx[sn]]['title'][:50]}")
        else:
            print("✗")
        time.sleep(0.5)

df_out = pd.DataFrame(rows)
df_out.to_csv(OUTPUT_CSV, index=False)

matched  = df_out[df_out["openalex_id"].fillna("") != ""].shape[0]
has_abs  = df_out[df_out["abstract"].fillna("").str.strip() != ""].shape[0]
is_oa    = df_out[df_out["is_oa"] == True].shape[0]
still_un = df_out[df_out["openalex_id"].fillna("") == ""][["SN","corpus_doi"]]

print(f"\n{'='*50}")
print(f"Output:       {OUTPUT_CSV}")
print(f"Matched:      {matched} / {len(df_out)}")
print(f"Unmatched:    {len(df_out) - matched}")
print(f"Has abstract: {has_abs}")
print(f"Open access:  {is_oa}")
if len(still_un):
    print(f"\nStill unmatched:")
    print(still_un.to_string())
print(f"\nSN1:  {df_out[df_out['SN']==1]['title'].values[0]}")
print(f"SN31: {df_out[df_out['SN']==31]['title'].values[0]}")
print(f"{'='*50}")
df_out[["SN", "title", "cited_by_count", "is_oa", "oa_status"]].head(5)

Loading corpus...
  519 papers loaded
  DOI override: SN 75 -> 10.48550/arxiv.2308.10149
  515 DOIs to fetch

Chunk 1: fetching 50 DOIs...

got 47

Chunk 2: fetching 50 DOIs...

got 49

Chunk 3: fetching 50 DOIs...

got 50

Chunk 4: fetching 50 DOIs...

got 50

Chunk 5: fetching 50 DOIs...

got 50

Chunk 6: fetching 50 DOIs...

got 48

Chunk 7: fetching 50 DOIs...

got 50

Chunk 8: fetching 50 DOIs...

got 50

Chunk 9: fetching 50 DOIs...

got 50

Chunk 10: fetching 50 DOIs...

got 50

Chunk 11: fetching 15 DOIs...

got 15

Total fetched from batch: 509

Lookup table: 499 entries

Force re-fetching known wrong matches...
  SN 1...

✓ Diagnosing bias in data-driven algorithms for healthcare

Individual fallback for unmatched DOI papers...
  SN 10 (10.48550/arxiv.2206.02237)...

✓ Enforcing Group Fairness in Algorithmic Decision M

  SN 21 (10.48550/arxiv.2110.00530)...

✓ A survey on datasets for fairness-aware machine le

  SN 26 (10.48550/arxiv.1801.07593)...

✗ not found via DOI, trying title...

    ✓ title match: Mitigating Unwanted Biases with Adversarial Learni

  SN 31 (10.48550/arxiv.1908.09635)...

✗ not found via DOI, trying title...

    ✓ title match: A Survey on Bias and Fairness in Machine Learning

  SN 35 (10.48550/arxiv.2109.14376)...

✓ Fairness-Driven Private Collaborative Machine Lear

  SN 55 (10.5281/zenodo.3912064)...

✓ Accepted Artifact Package for ESEC/FSE 2020 paper:

  SN 93 (10.1145/3708359.3712111)...

✓ Unequal Opportunities: Examining the Bias in Geogr

  SN 308 (10.1109/wacv61042.2026.00719)...

✓ FairVLM: Enhancing Fairness and Prompt Sensitivity

  SN 367 (10.48550/arxiv.1808.00023)...

✓ The Measure and Mismeasure of Fairness

Title-search for 4 no-DOI papers...
  SN 33: Fairness and Machine Learning: Limitations and Opportunities...

✓ Ethical limitations of algorithmic fairness soluti

  SN 58: Fairness-Aware Machine Learning: An Extensive Overview...

✓ Fairness and privacy preserving in federated learn

  SN 90: Understanding Asian Stereotyping and Bias in LLMs...

✓ Can Large Language Models Transform Computational

  SN 91: Evaluating Interfaced LLM Bias...

✓ Assessing the potential of GPT-4 to perpetuate rac

==================================================
Output:       openalex_enriched.csv
Matched:      519 / 519
Unmatched:    0
Has abstract: 457
Open access:  364

SN1:  Diagnosing bias in data-driven algorithms for healthcare
SN31: A Survey on Bias and Fairness in Machine Learning
==================================================

,SN,title,cited_by_count,is_oa,oa_status
0,1,Diagnosing bias in data-driven algorithms for ...,62,False,closed
1,2,Artificial intelligence and algorithmic bias: ...,499,True,gold
2,3,Artificial Intelligence in Clinical Decision S...,335,True,hybrid
3,4,Artificial intelligence bias in medical system...,57,True,bronze
4,5,Inherent Bias in Artificial Intelligence-Based...,46,True,gold